import modelUrl from "/map.glb?url";
import Label from "./Label";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle013: THREE.Mesh;
    Circle013_1: THREE.Mesh;
    Circle013_2: THREE.Mesh;
    Circle013_3: THREE.Mesh;
    篮球场: THREE.Mesh;
    空间研究院: THREE.Mesh;
    艺术楼: THREE.Mesh;
    Circle003: THREE.Mesh;
    Circle003_1: THREE.Mesh;
    Circle003_2: THREE.Mesh;
    Circle003_3: THREE.Mesh;
    网球羽毛球场: THREE.Mesh;
    网球场: THREE.Mesh;
    研究生院: THREE.Mesh;
    篮球场001: THREE.Mesh;
    留园: THREE.Mesh;
    篮球场002: THREE.Mesh;
    理科生命大楼B区: THREE.Mesh;
    理科生命大楼A区: THREE.Mesh;
    环境楼: THREE.Mesh;
    湖: THREE.Mesh;
    白帆运动场: THREE.Mesh;
    汽车电子楼: THREE.Mesh;
    水电楼: THREE.Mesh;
    水利馆: THREE.Mesh;
    第56实验大楼: THREE.Mesh;
    正气广场: THREE.Mesh;
    第12实验大楼: THREE.Mesh;
    材料楼: THREE.Mesh;
    校医院: THREE.Mesh;
    机电楼: THREE.Mesh;
    服务大楼: THREE.Mesh;
    昌海楼: THREE.Mesh;
    法学楼: THREE.Mesh;
    建工楼B区: THREE.Mesh;
    建工楼A区: THREE.Mesh;
    天健垃圾场: THREE.Mesh;
    工程训练中心2: THREE.Mesh;
    ["天健园餐厅（九十食堂）"]: THREE.Mesh;
    天健30栋: THREE.Mesh;
    工程训练中心1: THREE.Mesh;
    天健29栋: THREE.Mesh;
    天健28栋: THREE.Mesh;
    安保楼: THREE.Mesh;
    天健27栋: THREE.Mesh;
    学府大道正门: THREE.Mesh;
    天健26栋: THREE.Mesh;
    天健25栋: THREE.Mesh;
    天健24栋: THREE.Mesh;
    天健23栋: THREE.Mesh;
    天健22栋: THREE.Mesh;
    天健21栋: THREE.Mesh;
    天健20栋: THREE.Mesh;
    天健19栋: THREE.Mesh;
    外经楼: THREE.Mesh;
    基础实验大楼: THREE.Mesh;
    地面: THREE.Mesh;
    图书馆: THREE.Mesh;
    国际学术交流中心: THREE.Mesh;
    国际公寓楼: THREE.Mesh;
    嘉言路北门001: THREE.Mesh;
    嘉言路北门: THREE.Mesh;
    办公楼: THREE.Mesh;
    前湖大道门: THREE.Mesh;
    六七食堂: THREE.Mesh;
    信工楼E区: THREE.Mesh;
    学工楼: THREE.Mesh;
    信工楼C区: THREE.Mesh;
    信工楼B区: THREE.Mesh;
    体育馆: THREE.Mesh;
    信工楼A区: THREE.Mesh;
    Circle016: THREE.Mesh;
    Circle016_1: THREE.Mesh;
    Circle016_2: THREE.Mesh;
    Circle016_3: THREE.Mesh;
    Circle014: THREE.Mesh;
    Circle014_1: THREE.Mesh;
    Circle014_2: THREE.Mesh;
    Circle014_3: THREE.Mesh;
    休闲8栋: THREE.Mesh;
    休闲6栋: THREE.Mesh;
    休闲9栋: THREE.Mesh;
    游泳馆001: THREE.Mesh;
    休闲4栋: THREE.Mesh;
    休闲7栋: THREE.Mesh;
    ["休闲6-7连接"]: THREE.Mesh;
    休闲3栋: THREE.Mesh;
    休闲1栋: THREE.Mesh;
    休闲17栋: THREE.Mesh;
    休闲15栋: THREE.Mesh;
    休闲12栋: THREE.Mesh;
    休闲5栋: THREE.Mesh;
    人文楼: THREE.Mesh;
    慧源楼: THREE.Mesh;
    休闲11栋: THREE.Mesh;
    休闲2栋: THREE.Mesh;
    三四食堂: THREE.Mesh;
    map_2osm_roads_secondary: THREE.Mesh;
    map_2osm_roads_residential: THREE.Mesh;
    map_2osm_roads_primary: THREE.Mesh;
    map_2osm_forest: THREE.Mesh;
    休闲18栋: THREE.Mesh;
    休闲16栋: THREE.Mesh;
    休闲14栋: THREE.Mesh;
    休闲10栋: THREE.Mesh;
    一二食堂: THREE.Mesh;
    Plane014: THREE.Mesh;
    map_2osm_roads_service: THREE.Mesh;
    游泳馆: THREE.Mesh;
    Cube: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Grid: THREE.Mesh;
  };
  materials: {
    ["Playground Ground"]: THREE.MeshStandardMaterial;
    ["Football-Playground-mark.003"]: THREE.MeshStandardMaterial;
    ["Football Playground Dark.003"]: THREE.MeshStandardMaterial;
    ["Football Playground Light.003"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["water.001"]: THREE.MeshStandardMaterial;
    ["forest.001"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Swimming Pool Tile Procedural.001"]: THREE.MeshStandardMaterial;
    ["roads_secondary.001"]: THREE.MeshStandardMaterial;
    ["roads_residential.001"]: THREE.MeshStandardMaterial;
    ["roads_primary.001"]: THREE.MeshStandardMaterial;
    ["roads_service.001"]: THREE.MeshStandardMaterial;
    ["Square Grass"]: THREE.MeshStandardMaterial;
    ["Square Grey Stone"]: THREE.MeshStandardMaterial;
    ["Square Brown Stone"]: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(modelUrl) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="运动场004"
        position={[1.9005, -0.2962, 3.2102]}
        rotation={[0, 0.1845, 0]}
      >
        <mesh
          name="Circle013"
          castShadow
          receiveShadow
          geometry={nodes.Circle013.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle013_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle013_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle013_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <mesh
        name="篮球场"
        castShadow
        receiveShadow
        geometry={nodes.篮球场.geometry}
        material={materials["Material.003"]}
        position={[1.8827, -0.2941, 4.3709]}
        rotation={[0, 0.1848, 0]}

        children={<Label text="篮球场"></Label>}
      />
      <mesh
        name="空间研究院"
        castShadow
        receiveShadow
        geometry={nodes.空间研究院.geometry}
        material={nodes.空间研究院.material}
        position={[0.2309, -0.1891, 1.3919]}
        rotation={[0, -0.0479, 0]}

        children={<Label text="空间研究院"></Label>}
      />
      <mesh
        name="艺术楼"
        castShadow
        receiveShadow
        geometry={nodes.艺术楼.geometry}
        material={nodes.艺术楼.material}
        position={[-4.4528, -0.1625, -3.5528]}

        children={<Label text="艺术楼"></Label>}
      />
      <group
        name="运动场"
        position={[7.096, -0.3201, 5.2909]}
        rotation={[0, -0.1738, 0]}
      >
        <mesh
          name="Circle003"
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle003_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle003_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle003_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle003_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle003_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle003_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <mesh
        name="网球羽毛球场"
        castShadow
        receiveShadow
        geometry={nodes.网球羽毛球场.geometry}
        material={nodes.网球羽毛球场.material}
        position={[-6.8061, -0.1948, -5.6277]}
        rotation={[-Math.PI, 1.1618, -Math.PI]}

        children={<Label text="网球羽毛球场"></Label>}
      />
      <mesh
        name="网球场"
        castShadow
        receiveShadow
        geometry={nodes.网球场.geometry}
        material={materials["Material.003"]}
        position={[2.1497, -0.2941, 3.844]}
        rotation={[0, 0.1848, 0]}

        children={<Label text="网球场"></Label>}
      />
      <mesh
        name="研究生院"
        castShadow
        receiveShadow
        geometry={nodes.研究生院.geometry}
        material={nodes.研究生院.material}
        position={[1.5952, -0.2309, 2.584]}
        rotation={[0, -1.5388, 0]}

        children={<Label text="研究生院"></Label>}
      />
      <mesh
        name="篮球场001"
        castShadow
        receiveShadow
        geometry={nodes.篮球场001.geometry}
        material={materials["Material.003"]}
        position={[1.8649, -0.2941, 4.3742]}
        rotation={[0, 0.1848, 0]}

        children={<Label text="篮球场001"></Label>}
      />
      <mesh
        name="留园"
        castShadow
        receiveShadow
        geometry={nodes.留园.geometry}
        material={nodes.留园.material}
        position={[-3.5739, -0.1998, -6.4287]}
        rotation={[Math.PI, -0.2317, Math.PI]}

        children={<Label text="留园"></Label>}
      />
      <mesh
        name="篮球场002"
        castShadow
        receiveShadow
        geometry={nodes.篮球场002.geometry}
        material={materials["Material.003"]}
        position={[2.4629, -0.2941, 4.2624]}
        rotation={[0, 0.1848, 0]}

        children={<Label text="篮球场002"></Label>}
      />
      <mesh
        name="理科生命大楼B区"
        castShadow
        receiveShadow
        geometry={nodes.理科生命大楼B区.geometry}
        material={nodes.理科生命大楼B区.material}
        position={[-2.0771, -0.1008, 2.7343]}
        rotation={[0, 0.1952, 0]}

        children={<Label text="理科生命大楼B区"></Label>}
      />
      <mesh
        name="理科生命大楼A区"
        castShadow
        receiveShadow
        geometry={nodes.理科生命大楼A区.geometry}
        material={nodes.理科生命大楼A区.material}
        position={[-1.7437, -0.1008, 2.6684]}
        rotation={[0, 0.1952, 0]}

        children={<Label text="理科生命大楼A区"></Label>}
      />
      <mesh
        name="环境楼"
        castShadow
        receiveShadow
        geometry={nodes.环境楼.geometry}
        material={nodes.环境楼.material}
        position={[-2.5279, -0.1648, 3.2517]}
        rotation={[Math.PI, -0.197, Math.PI]}

        children={<Label text="环境楼"></Label>}
      />
      <mesh
        name="湖"
        castShadow
        receiveShadow
        geometry={nodes.湖.geometry}
        material={materials["water.001"]}
        position={[0.5678, -0.3824, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}

        children={<Label text="湖"></Label>}
      />
      <mesh
        name="白帆运动场"
        castShadow
        receiveShadow
        geometry={nodes.白帆运动场.geometry}
        material={nodes.白帆运动场.material}
        position={[-5.5256, -0.2501, -5.575]}

        children={<Label text="白帆运动场"></Label>}
      />
      <mesh
        name="汽车电子楼"
        castShadow
        receiveShadow
        geometry={nodes.汽车电子楼.geometry}
        material={nodes.汽车电子楼.material}
        position={[-4.7787, -0.1648, 1.8177]}
        rotation={[0, 0.1552, 0]}

        children={<Label text="汽车电子楼"></Label>}
      />
      <mesh
        name="水电楼"
        castShadow
        receiveShadow
        geometry={nodes.水电楼.geometry}
        material={nodes.水电楼.material}
        position={[-3.3046, -0.1648, 0.0244]}
        rotation={[0, -0.2218, 0]}

        children={<Label text="水电楼"></Label>}
      />
      <mesh
        name="水利馆"
        castShadow
        receiveShadow
        geometry={nodes.水利馆.geometry}
        material={nodes.水利馆.material}
        position={[-5.7689, -0.2338, 1.3527]}
        rotation={[0, 0.7614, 0]}

        children={<Label text="水利馆"></Label>}
      />
      <mesh
        name="第56实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.第56实验大楼.geometry}
        material={nodes.第56实验大楼.material}
        position={[6.9132, -0.2963, 4.126]}

        children={<Label text="第56实验大楼"></Label>}
      />
      <mesh
        name="正气广场"
        castShadow
        receiveShadow
        geometry={nodes.正气广场.geometry}
        material={materials["forest.001"]}
        position={[-3.0741, -0.2865, -2.4768]}

        children={<Label text="正气广场"></Label>}
      />
      <mesh
        name="第12实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.第12实验大楼.geometry}
        material={nodes.第12实验大楼.material}
        position={[6.9768, -0.2963, 2.6236]}

        children={<Label text="第12实验大楼"></Label>}
      />
      <mesh
        name="材料楼"
        castShadow
        receiveShadow
        geometry={nodes.材料楼.geometry}
        material={nodes.材料楼.material}
        position={[-2.6795, -0.1648, 2.5115]}
        rotation={[0, 0.197, 0]}

        children={<Label text="材料楼"></Label>}
      />
      <mesh
        name="校医院"
        castShadow
        receiveShadow
        geometry={nodes.校医院.geometry}
        material={nodes.校医院.material}
        position={[-6.5109, -0.1651, -3.7505]}

        children={<Label text="校医院"></Label>}
      />
      <mesh
        name="机电楼"
        castShadow
        receiveShadow
        geometry={nodes.机电楼.geometry}
        material={nodes.机电楼.material}
        position={[-4.4515, -0.1648, 1.6126]}
        rotation={[0, 0.1552, 0]}

        children={<Label text="机电楼"></Label>}
      />
      <mesh
        name="服务大楼"
        castShadow
        receiveShadow
        geometry={nodes.服务大楼.geometry}
        material={nodes.服务大楼.material}
        position={[-0.6538, -0.2309, 3.4355]}
        rotation={[-Math.PI, 1.5388, -Math.PI]}

        children={<Label text="服务大楼"></Label>}
      />
      <mesh
        name="昌海楼"
        castShadow
        receiveShadow
        geometry={nodes.昌海楼.geometry}
        material={nodes.昌海楼.material}
        position={[3.4794, -0.1757, 2.0434]}
        rotation={[0, 0.208, 0]}

        children={<Label text="昌海楼"></Label>}
      />
      <mesh
        name="法学楼"
        castShadow
        receiveShadow
        geometry={nodes.法学楼.geometry}
        material={nodes.法学楼.material}
        position={[-3.995, -0.1014, -1.1964]}
        rotation={[0, 0.1913, 0]}

        children={<Label text="法学楼"></Label>}
      />
      <mesh
        name="建工楼B区"
        castShadow
        receiveShadow
        geometry={nodes.建工楼B区.geometry}
        material={nodes.建工楼B区.material}
        position={[-5.5462, -0.1648, 1.006]}
        rotation={[0, 0.4128, 0]}

        children={<Label text="建工楼B区"></Label>}
      />
      <mesh
        name="建工楼A区"
        castShadow
        receiveShadow
        geometry={nodes.建工楼A区.geometry}
        material={nodes.建工楼A区.material}
        position={[-5.1788, -0.1648, 1.2066]}
        rotation={[0, 0.1829, 0]}

        children={<Label text="建工楼A区"></Label>}
      />
      <mesh
        name="天健垃圾场"
        castShadow
        receiveShadow
        geometry={nodes.天健垃圾场.geometry}
        material={nodes.天健垃圾场.material}
        position={[-1.7689, -0.2427, 3.6811]}
        rotation={[0, 0.1448, 0]}

        children={<Label text="天健垃圾场"></Label>}
      />
      <mesh
        name="工程训练中心2"
        castShadow
        receiveShadow
        geometry={nodes.工程训练中心2.geometry}
        material={nodes.工程训练中心2.material}
        position={[0.8188, -0.0766, 2.3765]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="工程训练中心2"></Label>}
      />
      <mesh
        name="天健园餐厅（九十食堂）"
        castShadow
        receiveShadow
        geometry={nodes["天健园餐厅（九十食堂）"].geometry}
        material={nodes["天健园餐厅（九十食堂）"].material}
        position={[-0.0298, -0.1408, 3.3809]}
        rotation={[0, 0.1815, 0]}
      />
      <mesh
        name="天健30栋"
        castShadow
        receiveShadow
        geometry={nodes.天健30栋.geometry}
        material={nodes.天健30栋.material}
        position={[3.5836, 0.0606, 3.0586]}
        rotation={[0, 0.208, 0]}

        children={<Label text="天健30栋"></Label>}
      />
      <mesh
        name="工程训练中心1"
        castShadow
        receiveShadow
        geometry={nodes.工程训练中心1.geometry}
        material={nodes.工程训练中心1.material}
        position={[0.3596, -0.0766, 2.2827]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="工程训练中心1"></Label>}
      />
      <mesh
        name="天健29栋"
        castShadow
        receiveShadow
        geometry={nodes.天健29栋.geometry}
        material={nodes.天健29栋.material}
        position={[3.1724, 0.0606, 3.018]}
        rotation={[0, 0.1813, 0]}

        children={<Label text="天健29栋"></Label>}
      />
      <mesh
        name="天健28栋"
        castShadow
        receiveShadow
        geometry={nodes.天健28栋.geometry}
        material={nodes.天健28栋.material}
        position={[2.7881, 0.0606, 3.1328]}
        rotation={[0, 0.1928, 0]}

        children={<Label text="天健28栋"></Label>}
      />
      <mesh
        name="安保楼"
        castShadow
        receiveShadow
        geometry={nodes.安保楼.geometry}
        material={nodes.安保楼.material}
        position={[-1.69, -0.1891, 1.6277]}
        rotation={[0, 0.1636, 0]}

        children={<Label text="安保楼"></Label>}
      />
      <mesh
        name="天健27栋"
        castShadow
        receiveShadow
        geometry={nodes.天健27栋.geometry}
        material={nodes.天健27栋.material}
        position={[1.0942, 0.0606, 4.0078]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="天健27栋"></Label>}
      />
      <mesh
        name="学府大道正门"
        castShadow
        receiveShadow
        geometry={nodes.学府大道正门.geometry}
        material={materials["Material.001"]}
        position={[0.6492, -0.339, -1.1597]}

        children={<Label text="学府大道正门"></Label>}
      />
      <mesh
        name="天健26栋"
        castShadow
        receiveShadow
        geometry={nodes.天健26栋.geometry}
        material={nodes.天健26栋.material}
        position={[0.9923, 0.0606, 3.343]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="天健26栋"></Label>}
      />
      <mesh
        name="天健25栋"
        castShadow
        receiveShadow
        geometry={nodes.天健25栋.geometry}
        material={nodes.天健25栋.material}
        position={[0.5962, 0.0606, 3.4204]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="天健25栋"></Label>}
      />
      <mesh
        name="天健24栋"
        castShadow
        receiveShadow
        geometry={nodes.天健24栋.geometry}
        material={nodes.天健24栋.material}
        position={[0.69, 0.0606, 4.0591]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="天健24栋"></Label>}
      />
      <mesh
        name="天健23栋"
        castShadow
        receiveShadow
        geometry={nodes.天健23栋.geometry}
        material={nodes.天健23栋.material}
        position={[0.152, 0.0606, 3.985]}
        rotation={[0, 0.1435, 0]}

        children={<Label text="天健23栋"></Label>}
      />
      <mesh
        name="天健22栋"
        castShadow
        receiveShadow
        geometry={nodes.天健22栋.geometry}
        material={nodes.天健22栋.material}
        position={[-0.2679, 0.0606, 3.8963]}
        rotation={[0, 0.1296, 0]}

        children={<Label text="天健22栋"></Label>}
      />
      <mesh
        name="天健21栋"
        castShadow
        receiveShadow
        geometry={nodes.天健21栋.geometry}
        material={nodes.天健21栋.material}
        position={[-0.6698, 0.0606, 3.838]}
        rotation={[0, 0.1293, 0]}

        children={<Label text="天健21栋"></Label>}
      />
      <mesh
        name="天健20栋"
        castShadow
        receiveShadow
        geometry={nodes.天健20栋.geometry}
        material={nodes.天健20栋.material}
        position={[-1.0451, 0.0606, 3.773]}
        rotation={[0, 0.1373, 0]}

        children={<Label text="天健20栋"></Label>}
      />
      <mesh
        name="天健19栋"
        castShadow
        receiveShadow
        geometry={nodes.天健19栋.geometry}
        material={nodes.天健19栋.material}
        position={[-1.3957, 0.0606, 3.7103]}
        rotation={[0, 0.1448, 0]}

        children={<Label text="天健19栋"></Label>}
      />
      <mesh
        name="外经楼"
        castShadow
        receiveShadow
        geometry={nodes.外经楼.geometry}
        material={nodes.外经楼.material}
        position={[-4.7671, -0.1631, -1.8555]}
        rotation={[0, 0.1735, 0]}

        children={<Label text="外经楼"></Label>}
      />
      <mesh
        name="基础实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.基础实验大楼.geometry}
        material={nodes.基础实验大楼.material}
        position={[-0.7777, -0.1031, 2.6472]}
        rotation={[0, 0.1952, 0]}

        children={<Label text="基础实验大楼"></Label>}
      />
      <mesh
        name="地面"
        castShadow
        receiveShadow
        geometry={nodes.地面.geometry}
        material={nodes.地面.material}
        position={[0.5678, -0.4303, -0.1349]}

        children={<Label text="地面"></Label>}
      />
      <mesh
        name="图书馆"
        castShadow
        receiveShadow
        geometry={nodes.图书馆.geometry}
        material={nodes.图书馆.material}
        position={[-0.5458, 0.3487, 1.5565]}
        rotation={[0, 0.183, 0]}

        children={<Label text="图书馆"></Label>}
      />
      <mesh
        name="国际学术交流中心"
        castShadow
        receiveShadow
        geometry={nodes.国际学术交流中心.geometry}
        material={nodes.国际学术交流中心.material}
        position={[3.9854, -0.075, 1.4943]}
        rotation={[Math.PI, -0.208, Math.PI]}

        children={<Label text="国际学术交流中心"></Label>}
      />
      <mesh
        name="国际公寓楼"
        castShadow
        receiveShadow
        geometry={nodes.国际公寓楼.geometry}
        material={nodes.国际公寓楼.material}
        position={[3.9448, 0.0606, 2.2367]}
        rotation={[0, 0.208, 0]}

        children={<Label text="国际公寓楼"></Label>}
      />
      <mesh
        name="嘉言路北门001"
        castShadow
        receiveShadow
        geometry={nodes.嘉言路北门001.geometry}
        material={materials["Material.019"]}
        position={[8.3244, -0.172, 0.5887]}
        rotation={[Math.PI / 2, 0, -3.0631]}

        children={<Label text="嘉言路北门001"></Label>}
      />
      <mesh
        name="嘉言路北门"
        castShadow
        receiveShadow
        geometry={nodes.嘉言路北门.geometry}
        material={materials["Material.019"]}
        position={[5.8705, -0.172, 2.3438]}
        rotation={[Math.PI / 2, 0, -1.7967]}

        children={<Label text="嘉言路北门"></Label>}
      />
      <mesh
        name="办公楼"
        castShadow
        receiveShadow
        geometry={nodes.办公楼.geometry}
        material={nodes.办公楼.material}
        position={[-1.3061, -0.1648, -1.4078]}
        rotation={[Math.PI, -0.9946, Math.PI]}

        children={<Label text="办公楼"></Label>}
      />
      <mesh
        name="前湖大道门"
        castShadow
        receiveShadow
        geometry={nodes.前湖大道门.geometry}
        material={materials["Material.019"]}
        position={[-8.1932, -0.2117, -5.6317]}
        rotation={[Math.PI / 2, 0, -0.6094]}

        children={<Label text="前湖大道门"></Label>}
      />
      <mesh
        name="六七食堂"
        castShadow
        receiveShadow
        geometry={nodes.六七食堂.geometry}
        material={nodes.六七食堂.material}
        position={[-8.5072, -0.1907, -2.6153]}
        rotation={[-Math.PI, 1.203, -Math.PI]}

        children={<Label text="六七食堂"></Label>}
      />
      <mesh
        name="信工楼E区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼E区.geometry}
        material={nodes.信工楼E区.material}
        position={[-4.2466, -0.1386, 2.4694]}
        rotation={[0, 0.2266, 0]}

        children={<Label text="信工楼E区"></Label>}
      />
      <mesh
        name="学工楼"
        castShadow
        receiveShadow
        geometry={nodes.学工楼.geometry}
        material={nodes.学工楼.material}
        position={[-7.406, -0.1209, -1.3641]}
        rotation={[-Math.PI, 1.3763, -Math.PI]}

        children={<Label text="学工楼"></Label>}
      />
      <mesh
        name="信工楼C区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼C区.geometry}
        material={nodes.信工楼C区.material}
        position={[-3.4109, -0.1386, 2.6763]}
        rotation={[0, 0.2266, 0]}

        children={<Label text="信工楼C区"></Label>}
      />
      <mesh
        name="信工楼B区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼B区.geometry}
        material={nodes.信工楼B区.material}
        position={[-3.4983, -0.1386, 2.2969]}
        rotation={[0, 0.2266, 0]}

        children={<Label text="信工楼B区"></Label>}
      />
      <mesh
        name="体育馆"
        castShadow
        receiveShadow
        geometry={nodes.体育馆.geometry}
        material={nodes.体育馆.material}
        position={[-3.4053, -0.1696, -5.7351]}
        rotation={[Math.PI, -0.2317, Math.PI]}

        children={<Label text="体育馆"></Label>}
      />
      <mesh
        name="信工楼A区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼A区.geometry}
        material={nodes.信工楼A区.material}
        position={[-3.4983, -0.1386, 2.2969]}
        rotation={[0, 0.2266, 0]}

        children={<Label text="信工楼A区"></Label>}
      />
      <group
        name="休闲运动场001"
        position={[-5.5223, -0.2345, -5.5789]}
        rotation={[Math.PI, -0.0083, Math.PI]}
      >
        <mesh
          name="Circle016"
          castShadow
          receiveShadow
          geometry={nodes.Circle016.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle016_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle016_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle016_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <group
        name="休闲运动场"
        position={[-8.5202, -0.3201, -4.1987]}
        rotation={[Math.PI, -0.1954, Math.PI]}
      >
        <mesh
          name="Circle014"
          castShadow
          receiveShadow
          geometry={nodes.Circle014.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle014_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle014_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle014_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <mesh
        name="休闲8栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲8栋.geometry}
        material={nodes.休闲8栋.material}
        position={[-7.6851, -0.2072, -1.9492]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲8栋"></Label>}
      />
      <mesh
        name="休闲6栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲6栋.geometry}
        material={nodes.休闲6栋.material}
        position={[-6.9896, -0.2088, -2.0261]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲6栋"></Label>}
      />
      <mesh
        name="休闲9栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲9栋.geometry}
        material={nodes.休闲9栋.material}
        position={[-7.3807, -0.2175, -3.4749]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲9栋"></Label>}
      />
      <mesh
        name="游泳馆001"
        castShadow
        receiveShadow
        geometry={nodes.游泳馆001.geometry}
        material={materials["Swimming Pool Tile Procedural.001"]}
        position={[-7.3117, -0.1625, -4.8339]}
        rotation={[0, 0.4907, 0]}

        children={<Label text="游泳馆001"></Label>}
      />
      <mesh
        name="休闲4栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲4栋.geometry}
        material={nodes.休闲4栋.material}
        position={[-7.6984, -0.1077, -0.919]}
        rotation={[0, 0.2422, 0]}

        children={<Label text="休闲4栋"></Label>}
      />
      <mesh
        name="休闲7栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲7栋.geometry}
        material={nodes.休闲7栋.material}
        position={[-7.4284, -0.2094, -1.9941]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲7栋"></Label>}
      />
      <mesh
        name="休闲6-7连接"
        castShadow
        receiveShadow
        geometry={nodes["休闲6-7连接"].geometry}
        material={nodes["休闲6-7连接"].material}
        position={[-7.2743, -0.1392, -2.1011]}
        rotation={[0, 0.192, 0]}
      />
      <mesh
        name="休闲3栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲3栋.geometry}
        material={nodes.休闲3栋.material}
        position={[-6.9812, -0.1386, -0.0693]}
        rotation={[0, 0.2047, 0]}

        children={<Label text="休闲3栋"></Label>}
      />
      <mesh
        name="休闲1栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲1栋.geometry}
        material={nodes.休闲1栋.material}
        position={[-6.1729, -0.1386, 0.5139]}
        rotation={[0, 0.2047, 0]}

        children={<Label text="休闲1栋"></Label>}
      />
      <mesh
        name="休闲17栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲17栋.geometry}
        material={nodes.休闲17栋.material}
        position={[-8.8404, -0.2175, -3.2351]}
        rotation={[0, 0.0802, 0]}

        children={<Label text="休闲17栋"></Label>}
      />
      <mesh
        name="休闲15栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲15栋.geometry}
        material={nodes.休闲15栋.material}
        position={[-8.8582, -0.1209, -2.5643]}
        rotation={[-Math.PI, 1.0674, -Math.PI]}

        children={<Label text="休闲15栋"></Label>}
      />
      <mesh
        name="休闲12栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲12栋.geometry}
        material={nodes.休闲12栋.material}
        position={[-8.2629, -0.2175, -3.3204]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲12栋"></Label>}
      />
      <mesh
        name="休闲5栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲5栋.geometry}
        material={nodes.休闲5栋.material}
        position={[-7.1943, -0.2039, -2.663]}
        rotation={[0, 0.165, 0]}

        children={<Label text="休闲5栋"></Label>}
      />
      <mesh
        name="人文楼"
        castShadow
        receiveShadow
        geometry={nodes.人文楼.geometry}
        material={nodes.人文楼.material}
        position={[-3.995, -0.1014, -1.1964]}
        rotation={[0, 0.1913, 0]}

        children={<Label text="人文楼"></Label>}
      />
      <mesh
        name="慧源楼"
        castShadow
        receiveShadow
        geometry={nodes.慧源楼.geometry}
        material={nodes.慧源楼.material}
        position={[-5.8897, -0.1901, -0.6416]}
        rotation={[0, 0.5643, 0]}

        children={<Label text="慧源楼"></Label>}
      />
      <mesh
        name="休闲11栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲11栋.geometry}
        material={nodes.休闲11栋.material}
        position={[-7.9558, -0.2175, -3.3742]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲11栋"></Label>}
      />
      <mesh
        name="休闲2栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲2栋.geometry}
        material={nodes.休闲2栋.material}
        position={[-6.5088, -0.1386, 0.5836]}
        rotation={[0, 0.2047, 0]}

        children={<Label text="休闲2栋"></Label>}
      />
      <mesh
        name="三四食堂"
        castShadow
        receiveShadow
        geometry={nodes.三四食堂.geometry}
        material={nodes.三四食堂.material}
        position={[-7.6874, -0.2251, -2.7678]}
        rotation={[-Math.PI, 1.3891, -Math.PI]}

        children={<Label text="三四食堂"></Label>}
      />
      <mesh
        name="map_2osm_roads_secondary"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_secondary.geometry}
        material={materials["roads_secondary.001"]}
        position={[0.5678, -0.294, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}
      />
      <mesh
        name="map_2osm_roads_residential"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_residential.geometry}
        material={materials["roads_residential.001"]}
        position={[0.5678, -0.294, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}
      />
      <mesh
        name="map_2osm_roads_primary"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_primary.geometry}
        material={materials["roads_primary.001"]}
        position={[0.5678, -0.294, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}
      />
      <mesh
        name="map_2osm_forest"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_forest.geometry}
        material={materials["forest.001"]}
        position={[0.5678, -0.2953, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}
      />
      <mesh
        name="休闲18栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲18栋.geometry}
        material={nodes.休闲18栋.material}
        position={[-9.2049, -0.1209, -3.1938]}
        rotation={[-Math.PI, 1.0674, -Math.PI]}

        children={<Label text="休闲18栋"></Label>}
      />
      <mesh
        name="休闲16栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲16栋.geometry}
        material={nodes.休闲16栋.material}
        position={[-8.561, -0.2175, -3.2523]}
        rotation={[0, 0.0802, 0]}

        children={<Label text="休闲16栋"></Label>}
      />
      <mesh
        name="休闲14栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲14栋.geometry}
        material={nodes.休闲14栋.material}
        position={[-8.5074, -0.1209, -1.9273]}
        rotation={[-Math.PI, 1.0674, -Math.PI]}

        children={<Label text="休闲14栋"></Label>}
      />
      <mesh
        name="休闲10栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲10栋.geometry}
        material={nodes.休闲10栋.material}
        position={[-7.6785, -0.2175, -3.4228]}
        rotation={[0, 0.1922, 0]}

        children={<Label text="休闲10栋"></Label>}
      />
      <mesh
        name="一二食堂"
        castShadow
        receiveShadow
        geometry={nodes.一二食堂.geometry}
        material={nodes.一二食堂.material}
        position={[-6.6254, -0.2119, -0.4059]}
        rotation={[0, 0.3315, 0]}

        children={<Label text="一二食堂"></Label>}
      />
      <mesh
        name="Plane014"
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["forest.001"]}
        position={[-2.8155, -0.2881, 1.809]}
        rotation={[0, 0.1788, 0]}
      />
      <mesh
        name="map_2osm_roads_service"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_service.geometry}
        material={materials["roads_service.001"]}
        position={[0.5678, -0.294, -0.1349]}
        rotation={[-Math.PI, 1.3847, -Math.PI]}
      />
      <mesh
        name="游泳馆"
        castShadow
        receiveShadow
        geometry={nodes.游泳馆.geometry}
        material={nodes.游泳馆.material}
        position={[-7.3117, -0.1727, -4.8339]}
        rotation={[0, 0.4907, 0]}

        children={<Label text="游泳馆"></Label>}
      />
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[10.3217, 0.2191, 5.6267]}
        rotation={[0, -0.1813, 0]}
      />
      <group name="Circle" position={[8.2723, -0.3759, 2.4596]}>
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Square Grass"]}
        />
        <mesh
          name="Circle001_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials["Square Grey Stone"]}
        />
        <mesh
          name="Circle001_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials["Square Brown Stone"]}
        />
      </group>
      <mesh
        name="Grid"
        castShadow
        receiveShadow
        geometry={nodes.Grid.geometry}
        material={materials["water.001"]}
        position={[8.9144, -0.3909, 3.0841]}
      />
    </group>
  );
}

useGLTF.preload(modelUrl);