import modelUrl from "/models/map.glb?url";
import Label from "./Label";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    休闲6栋: THREE.Mesh;
    休闲7栋: THREE.Mesh;
    休闲8栋: THREE.Mesh;
    休闲10栋: THREE.Mesh;
    休闲9栋: THREE.Mesh;
    休闲11栋: THREE.Mesh;
    休闲12栋: THREE.Mesh;
    休闲16栋: THREE.Mesh;
    休闲17栋: THREE.Mesh;
    三四食堂: THREE.Mesh;
    六七食堂: THREE.Mesh;
    休闲14栋: THREE.Mesh;
    休闲15栋: THREE.Mesh;
    休闲18栋: THREE.Mesh;
    学工楼: THREE.Mesh;
    休闲4栋: THREE.Mesh;
    ["休闲6-7连接"]: THREE.Mesh;
    休闲5栋: THREE.Mesh;
    休闲1栋: THREE.Mesh;
    休闲2栋: THREE.Mesh;
    休闲3栋: THREE.Mesh;
    一二食堂: THREE.Mesh;
    慧源楼: THREE.Mesh;
    外经楼: THREE.Mesh;
    艺术楼: THREE.Mesh;
    校医院: THREE.Mesh;
    游泳馆: THREE.Mesh;
    人文楼: THREE.Mesh;
    法学楼: THREE.Mesh;
    前湖大道门: THREE.Mesh;
    学府大道正门: THREE.Mesh;
    白帆运动场: THREE.Mesh;
    嘉言路北门: THREE.Mesh;
    嘉言路北门001: THREE.Mesh;
    网球羽毛球场: THREE.Mesh;
    体育馆: THREE.Mesh;
    留园: THREE.Mesh;
    水利馆: THREE.Mesh;
    建工楼A区: THREE.Mesh;
    建工楼B区: THREE.Mesh;
    汽车电子楼: THREE.Mesh;
    机电楼: THREE.Mesh;
    信工楼B区: THREE.Mesh;
    信工楼A区: THREE.Mesh;
    信工楼C区: THREE.Mesh;
    信工楼E区: THREE.Mesh;
    材料楼: THREE.Mesh;
    环境楼: THREE.Mesh;
    理科生命大楼B区: THREE.Mesh;
    理科生命大楼A区: THREE.Mesh;
    天健19栋: THREE.Mesh;
    天健20栋: THREE.Mesh;
    天健21栋: THREE.Mesh;
    天健22栋: THREE.Mesh;
    天健23栋: THREE.Mesh;
    天健24栋: THREE.Mesh;
    天健27栋: THREE.Mesh;
    天健26栋: THREE.Mesh;
    天健25栋: THREE.Mesh;
    基础实验大楼: THREE.Mesh;
    服务大楼: THREE.Mesh;
    ["天健园餐厅（九十食堂）"]: THREE.Mesh;
    工程训练中心1: THREE.Mesh;
    工程训练中心2: THREE.Mesh;
    研究生院: THREE.Mesh;
    天健28栋: THREE.Mesh;
    天健29栋: THREE.Mesh;
    天健30栋: THREE.Mesh;
    国际公寓楼: THREE.Mesh;
    国际学术交流中心: THREE.Mesh;
    昌海楼: THREE.Mesh;
    空间研究院: THREE.Mesh;
    图书馆: THREE.Mesh;
    安保楼: THREE.Mesh;
    天健垃圾场: THREE.Mesh;
    第12实验大楼: THREE.Mesh;
    第56实验大楼: THREE.Mesh;
    水电楼: THREE.Mesh;
    办公楼: THREE.Mesh;
    swimPool: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    人才公寓1栋: THREE.Mesh;
    map_2osm_forest: THREE.Mesh;
    map_2osm_roads_primary: THREE.Mesh;
    map_2osm_roads_residential: THREE.Mesh;
    map_2osm_roads_secondary: THREE.Mesh;
    map_2osm_roads_service: THREE.Mesh;
    湖: THREE.Mesh;
    正气广场: THREE.Mesh;
    Plane014: THREE.Mesh;
    网球场: THREE.Mesh;
    basketballCount: THREE.Mesh;
    篮球场: THREE.Mesh;
    basketballCourt: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle005_1: THREE.Mesh;
    Circle005_2: THREE.Mesh;
    Circle005_3: THREE.Mesh;
    Circle014: THREE.Mesh;
    Circle014_1: THREE.Mesh;
    Circle014_2: THREE.Mesh;
    Circle014_3: THREE.Mesh;
    Circle013: THREE.Mesh;
    Circle013_1: THREE.Mesh;
    Circle013_2: THREE.Mesh;
    Circle013_3: THREE.Mesh;
    Circle016: THREE.Mesh;
    Circle016_1: THREE.Mesh;
    Circle016_2: THREE.Mesh;
    Circle016_3: THREE.Mesh;
    月亮湖: THREE.Mesh;
    floor: THREE.Mesh;
  };
  materials: {
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Swimming Pool Tile Procedural.001"]: THREE.MeshStandardMaterial;
    ["Square Grass"]: THREE.MeshStandardMaterial;
    ["Square Grey Stone"]: THREE.MeshStandardMaterial;
    ["Square Brown Stone"]: THREE.MeshStandardMaterial;
    ["forest.001"]: THREE.MeshStandardMaterial;
    ["roads_primary.001"]: THREE.MeshStandardMaterial;
    ["roads_residential.001"]: THREE.MeshStandardMaterial;
    ["roads_secondary.001"]: THREE.MeshStandardMaterial;
    ["roads_service.001"]: THREE.MeshStandardMaterial;
    ["water.001"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Playground Ground"]: THREE.MeshStandardMaterial;
    ["Football-Playground-mark.003"]: THREE.MeshStandardMaterial;
    ["Football Playground Dark.003"]: THREE.MeshStandardMaterial;
    ["Football Playground Light.003"]: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(modelUrl) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="休闲6栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲6栋.geometry}
        material={nodes.休闲6栋.material}
        position={[-7.93878, 0.30451, -1.0913]}
        children={<Label text="休闲6栋"></Label>}
      />
      <mesh
        name="休闲7栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲7栋.geometry}
        material={nodes.休闲7栋.material}
        position={[-8.3775, 0.30394, -1.05933]}
        children={<Label text="休闲7栋"></Label>}
      />
      <mesh
        name="休闲8栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲8栋.geometry}
        material={nodes.休闲8栋.material}
        position={[-8.63422, 0.30619, -1.01439]}
        children={<Label text="休闲8栋"></Label>}
      />
      <mesh
        name="休闲10栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲10栋.geometry}
        material={nodes.休闲10栋.material}
        position={[-8.62762, 0.4146, -2.48796]}
        children={<Label text="休闲10栋"></Label>}
      />
      <mesh
        name="休闲9栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲9栋.geometry}
        material={nodes.休闲9栋.material}
        position={[-8.3298, 0.29588, -2.54012]}
        children={<Label text="休闲9栋"></Label>}
      />
      <mesh
        name="休闲11栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲11栋.geometry}
        material={nodes.休闲11栋.material}
        position={[-8.90491, 0.29588, -2.43938]}
        children={<Label text="休闲11栋"></Label>}
      />
      <mesh
        name="休闲12栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲12栋.geometry}
        material={nodes.休闲12栋.material}
        position={[-9.21198, 0.29588, -2.38563]}
        children={<Label text="休闲12栋"></Label>}
      />
      <mesh
        name="休闲16栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲16栋.geometry}
        material={nodes.休闲16栋.material}
        position={[-9.51007, 0.29588, -2.31753]}
        children={<Label text="休闲16栋"></Label>}
      />
      <mesh
        name="休闲17栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲17栋.geometry}
        material={nodes.休闲17栋.material}
        position={[-9.78952, 0.29588, -2.30036]}
        children={<Label text="休闲17栋"></Label>}
      />
      <mesh
        name="三四食堂"
        castShadow
        receiveShadow
        geometry={nodes.三四食堂.geometry}
        material={nodes.三四食堂.material}
        position={[-8.63651, 0.39759, -1.83302]}
        children={<Label text="三四食堂"></Label>}
      />
      <mesh
        name="六七食堂"
        castShadow
        receiveShadow
        geometry={nodes.六七食堂.geometry}
        material={nodes.六七食堂.material}
        position={[-9.4563, 0.32266, -1.68049]}
        children={<Label text="六七食堂"></Label>}
      />
      <mesh
        name="休闲14栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲14栋.geometry}
        material={nodes.休闲14栋.material}
        position={[-9.45645, 0.39244, -0.9925]}
        children={<Label text="休闲14栋"></Label>}
      />
      <mesh
        name="休闲15栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲15栋.geometry}
        material={nodes.休闲15栋.material}
        position={[-9.80728, 0.39244, -1.6295]}
        children={<Label text="休闲15栋"></Label>}
      />
      <mesh
        name="休闲18栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲18栋.geometry}
        material={nodes.休闲18栋.material}
        position={[-10.15396, 0.39244, -2.259]}
        children={<Label text="休闲18栋"></Label>}
      />
      <mesh
        name="学工楼"
        castShadow
        receiveShadow
        geometry={nodes.学工楼.geometry}
        material={nodes.学工楼.material}
        position={[-8.3551, 0.62558, -0.42931]}
        children={<Label text="学工楼"></Label>}
      />
      <mesh
        name="休闲4栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲4栋.geometry}
        material={nodes.休闲4栋.material}
        position={[-8.64749, 0.40567, 0.01582]}
        children={<Label text="休闲4栋"></Label>}
      />
      <mesh
        name="休闲6-7连接"
        castShadow
        receiveShadow
        geometry={nodes["休闲6-7连接"].geometry}
        material={nodes["休闲6-7连接"].material}
        position={[-8.22339, 0.3937, -1.16634]}
      />
      <mesh
        name="休闲5栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲5栋.geometry}
        material={nodes.休闲5栋.material}
        position={[-8.14334, 0.41091, -1.72822]}
        children={<Label text="休闲5栋"></Label>}
      />
      <mesh
        name="休闲1栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲1栋.geometry}
        material={nodes.休闲1栋.material}
        position={[-7.12204, 0.54541, 1.44865]}
        children={<Label text="休闲1栋"></Label>}
      />
      <mesh
        name="休闲2栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲2栋.geometry}
        material={nodes.休闲2栋.material}
        position={[-7.45792, 0.37477, 1.51838]}
        children={<Label text="休闲2栋"></Label>}
      />
      <mesh
        name="休闲3栋"
        castShadow
        receiveShadow
        geometry={nodes.休闲3栋.geometry}
        material={nodes.休闲3栋.material}
        position={[-7.93033, 0.37477, 0.86553]}
        children={<Label text="休闲3栋"></Label>}
      />
      <mesh
        name="一二食堂"
        castShadow
        receiveShadow
        geometry={nodes.一二食堂.geometry}
        material={nodes.一二食堂.material}
        position={[-7.57446, 0.38597, 0.52894]}
        children={<Label text="一二食堂"></Label>}
      />
      <mesh
        name="慧源楼"
        castShadow
        receiveShadow
        geometry={nodes.慧源楼.geometry}
        material={nodes.慧源楼.material}
        position={[-6.83875, 0.42833, 0.29317]}
        children={<Label text="慧源楼"></Label>}
      />
      <mesh
        name="外经楼"
        castShadow
        receiveShadow
        geometry={nodes.外经楼.geometry}
        material={nodes.外经楼.material}
        position={[-5.71619, 0.47335, -0.92069]}
        children={<Label text="外经楼"></Label>}
      />
      <mesh
        name="艺术楼"
        castShadow
        receiveShadow
        geometry={nodes.艺术楼.geometry}
        material={nodes.艺术楼.material}
        position={[-5.40189, 0.48214, -2.61805]}
        children={<Label text="艺术楼"></Label>}
      />
      <mesh
        name="校医院"
        castShadow
        receiveShadow
        geometry={nodes.校医院.geometry}
        material={nodes.校医院.material}
        position={[-7.46002, 0.47947, -2.8157]}
        children={<Label text="校医院"></Label>}
      />
      <mesh
        name="游泳馆"
        castShadow
        receiveShadow
        geometry={nodes.游泳馆.geometry}
        material={nodes.游泳馆.material}
        position={[-8.2608, 0.58716, -3.89916]}
        children={<Label text="游泳馆"></Label>}
      />
      <mesh
        name="人文楼"
        castShadow
        receiveShadow
        geometry={nodes.人文楼.geometry}
        material={nodes.人文楼.material}
        position={[-4.944, 0.60992, -0.26165]}
        children={<Label text="人文楼"></Label>}
      />
      <mesh
        name="法学楼"
        castShadow
        receiveShadow
        geometry={nodes.法学楼.geometry}
        material={nodes.法学楼.material}
        position={[-4.944, 0.60971, -0.26165]}
        children={<Label text="法学楼"></Label>}
      />
      <mesh
        name="前湖大道门"
        castShadow
        receiveShadow
        geometry={nodes.前湖大道门.geometry}
        material={materials["Material.019"]}
        position={[-9.14227, 0.38437, -4.69691]}
        children={<Label text="前湖大道门"></Label>}
      />
      <mesh
        name="学府大道正门"
        castShadow
        receiveShadow
        geometry={nodes.学府大道正门.geometry}
        material={materials["Material.001"]}
        position={[-0.29987, 0.21737, -0.22495]}
        children={<Label text="学府大道正门"></Label>}
      />
      <mesh
        name="白帆运动场"
        castShadow
        receiveShadow
        geometry={nodes.白帆运动场.geometry}
        material={nodes.白帆运动场.material}
        position={[-6.47467, 0.5153, -4.64024]}
        children={<Label text="白帆运动场"></Label>}
      />
      <mesh
        name="嘉言路北门"
        castShadow
        receiveShadow
        geometry={nodes.嘉言路北门.geometry}
        material={materials["Material.019"]}
        position={[4.92142, 0.3413, 3.27861]}
        children={<Label text="嘉言路北门"></Label>}
      />
      <mesh
        name="嘉言路北门001"
        castShadow
        receiveShadow
        geometry={nodes.嘉言路北门001.geometry}
        material={materials["Material.019"]}
        position={[7.37543, 0.3413, 1.52351]}
        children={<Label text="嘉言路北门001"></Label>}
      />
      <mesh
        name="网球羽毛球场"
        castShadow
        receiveShadow
        geometry={nodes.网球羽毛球场.geometry}
        material={nodes.网球羽毛球场.material}
        position={[-7.75519, 0.41475, -4.69292]}
        children={<Label text="网球羽毛球场"></Label>}
      />
      <mesh
        name="体育馆"
        castShadow
        receiveShadow
        geometry={nodes.体育馆.geometry}
        material={nodes.体育馆.material}
        position={[-4.3544, 0.46859, -4.80031]}
        children={<Label text="体育馆"></Label>}
      />
      <mesh
        name="留园"
        castShadow
        receiveShadow
        geometry={nodes.留园.geometry}
        material={nodes.留园.material}
        position={[-4.52295, 0.40977, -5.49388]}
        children={<Label text="留园"></Label>}
      />
      <mesh
        name="水利馆"
        castShadow
        receiveShadow
        geometry={nodes.水利馆.geometry}
        material={nodes.水利馆.material}
        position={[-6.71799, 0.33978, 2.28751]}
        children={<Label text="水利馆"></Label>}
      />
      <mesh
        name="建工楼A区"
        castShadow
        receiveShadow
        geometry={nodes.建工楼A区.geometry}
        material={nodes.建工楼A区.material}
        position={[-6.1279, 0.47732, 2.14141]}
        children={<Label text="建工楼A区"></Label>}
      />
      <mesh
        name="建工楼B区"
        castShadow
        receiveShadow
        geometry={nodes.建工楼B区.geometry}
        material={nodes.建工楼B区.material}
        position={[-6.49533, 0.47732, 1.94085]}
        children={<Label text="建工楼B区"></Label>}
      />
      <mesh
        name="汽车电子楼"
        castShadow
        receiveShadow
        geometry={nodes.汽车电子楼.geometry}
        material={nodes.汽车电子楼.material}
        position={[-5.72778, 0.47732, 2.75255]}
        children={<Label text="汽车电子楼"></Label>}
      />
      <mesh
        name="机电楼"
        castShadow
        receiveShadow
        geometry={nodes.机电楼.geometry}
        material={nodes.机电楼.material}
        position={[-5.4006, 0.47732, 2.54741]}
        children={<Label text="机电楼"></Label>}
      />
      <mesh
        name="信工楼B区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼B区.geometry}
        material={nodes.信工楼B区.material}
        position={[-4.44742, 0.54541, 3.23167]}
        children={<Label text="信工楼B区"></Label>}
      />
      <mesh
        name="信工楼A区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼A区.geometry}
        material={nodes.信工楼A区.material}
        position={[-4.44742, 0.54541, 3.23167]}
        children={<Label text="信工楼A区"></Label>}
      />
      <mesh
        name="信工楼C区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼C区.geometry}
        material={nodes.信工楼C区.material}
        position={[-4.35995, 0.54541, 3.61108]}
        children={<Label text="信工楼C区"></Label>}
      />
      <mesh
        name="信工楼E区"
        castShadow
        receiveShadow
        geometry={nodes.信工楼E区.geometry}
        material={nodes.信工楼E区.material}
        position={[-5.19568, 0.54541, 3.40417]}
        children={<Label text="信工楼E区"></Label>}
      />
      <mesh
        name="材料楼"
        castShadow
        receiveShadow
        geometry={nodes.材料楼.geometry}
        material={nodes.材料楼.material}
        position={[-3.62854, 0.52723, 3.44628]}
        children={<Label text="材料楼"></Label>}
      />
      <mesh
        name="环境楼"
        castShadow
        receiveShadow
        geometry={nodes.环境楼.geometry}
        material={nodes.环境楼.material}
        position={[-3.47693, 0.52723, 4.1865]}
        children={<Label text="环境楼"></Label>}
      />
      <mesh
        name="理科生命大楼B区"
        castShadow
        receiveShadow
        geometry={nodes.理科生命大楼B区.geometry}
        material={nodes.理科生命大楼B区.material}
        position={[-3.02612, 0.60401, 3.66908]}
        children={<Label text="理科生命大楼B区"></Label>}
      />
      <mesh
        name="理科生命大楼A区"
        castShadow
        receiveShadow
        geometry={nodes.理科生命大楼A区.geometry}
        material={nodes.理科生命大楼A区.material}
        position={[-2.69281, 0.60401, 3.60316]}
        children={<Label text="理科生命大楼A区"></Label>}
      />
      <mesh
        name="天健19栋"
        castShadow
        receiveShadow
        geometry={nodes.天健19栋.geometry}
        material={nodes.天健19栋.material}
        position={[-2.34476, 0.93458, 4.64506]}
        children={<Label text="天健19栋"></Label>}
      />
      <mesh
        name="天健20栋"
        castShadow
        receiveShadow
        geometry={nodes.天健20栋.geometry}
        material={nodes.天健20栋.material}
        position={[-1.9942, 0.93458, 4.70783]}
        children={<Label text="天健20栋"></Label>}
      />
      <mesh
        name="天健21栋"
        castShadow
        receiveShadow
        geometry={nodes.天健21栋.geometry}
        material={nodes.天健21栋.material}
        position={[-1.6188, 0.93458, 4.77282]}
        children={<Label text="天健21栋"></Label>}
      />
      <mesh
        name="天健22栋"
        castShadow
        receiveShadow
        geometry={nodes.天健22栋.geometry}
        material={nodes.天健22栋.material}
        position={[-1.21695, 0.93458, 4.83106]}
        children={<Label text="天健22栋"></Label>}
      />
      <mesh
        name="天健23栋"
        castShadow
        receiveShadow
        geometry={nodes.天健23栋.geometry}
        material={nodes.天健23栋.material}
        position={[-0.797, 0.93458, 4.91978]}
        children={<Label text="天健23栋"></Label>}
      />
      <mesh
        name="天健24栋"
        castShadow
        receiveShadow
        geometry={nodes.天健24栋.geometry}
        material={nodes.天健24栋.material}
        position={[-0.25903, 0.57397, 4.99392]}
        children={<Label text="天健24栋"></Label>}
      />
      <mesh
        name="天健27栋"
        castShadow
        receiveShadow
        geometry={nodes.天健27栋.geometry}
        material={nodes.天健27栋.material}
        position={[0.14517, 0.57397, 4.94263]}
        children={<Label text="天健27栋"></Label>}
      />
      <mesh
        name="天健26栋"
        castShadow
        receiveShadow
        geometry={nodes.天健26栋.geometry}
        material={nodes.天健26栋.material}
        position={[0.0433, 0.57397, 4.27776]}
        children={<Label text="天健26栋"></Label>}
      />
      <mesh
        name="天健25栋"
        castShadow
        receiveShadow
        geometry={nodes.天健25栋.geometry}
        material={nodes.天健25栋.material}
        position={[-0.35284, 0.57397, 4.35516]}
        children={<Label text="天健25栋"></Label>}
      />
      <mesh
        name="基础实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.基础实验大楼.geometry}
        material={nodes.基础实验大楼.material}
        position={[-1.72675, 0.60176, 3.58199]}
        children={<Label text="基础实验大楼"></Label>}
      />
      <mesh
        name="服务大楼"
        castShadow
        receiveShadow
        geometry={nodes.服务大楼.geometry}
        material={nodes.服务大楼.material}
        position={[-1.60287, 0.34388, 4.37029]}
        children={<Label text="服务大楼"></Label>}
      />
      <mesh
        name="天健园餐厅（九十食堂）"
        castShadow
        receiveShadow
        geometry={nodes["天健园餐厅（九十食堂）"].geometry}
        material={nodes["天健园餐厅（九十食堂）"].material}
        position={[-0.97888, 0.52351, 4.3157]}
      />
      <mesh
        name="工程训练中心1"
        castShadow
        receiveShadow
        geometry={nodes.工程训练中心1.geometry}
        material={nodes.工程训练中心1.material}
        position={[-0.58948, 0.65182, 3.21754]}
        children={<Label text="工程训练中心1"></Label>}
      />
      <mesh
        name="工程训练中心2"
        castShadow
        receiveShadow
        geometry={nodes.工程训练中心2.geometry}
        material={nodes.工程训练中心2.material}
        position={[-0.13028, 0.65182, 3.31135]}
        children={<Label text="工程训练中心2"></Label>}
      />
      <mesh
        name="研究生院"
        castShadow
        receiveShadow
        geometry={nodes.研究生院.geometry}
        material={nodes.研究生院.material}
        position={[0.64618, 0.36904, 3.51878]}
        children={<Label text="研究生院"></Label>}
      />
      <mesh
        name="天健28栋"
        castShadow
        receiveShadow
        geometry={nodes.天健28栋.geometry}
        material={nodes.天健28栋.material}
        position={[1.83902, 0.93458, 4.06763]}
        children={<Label text="天健28栋"></Label>}
      />
      <mesh
        name="天健29栋"
        castShadow
        receiveShadow
        geometry={nodes.天健29栋.geometry}
        material={nodes.天健29栋.material}
        position={[2.2233, 0.93458, 3.9528]}
        children={<Label text="天健29栋"></Label>}
      />
      <mesh
        name="天健30栋"
        castShadow
        receiveShadow
        geometry={nodes.天健30栋.geometry}
        material={nodes.天健30栋.material}
        position={[2.63458, 0.93458, 3.99339]}
        children={<Label text="天健30栋"></Label>}
      />
      <mesh
        name="国际公寓楼"
        castShadow
        receiveShadow
        geometry={nodes.国际公寓楼.geometry}
        material={nodes.国际公寓楼.material}
        position={[2.99576, 0.93458, 3.1715]}
        children={<Label text="国际公寓楼"></Label>}
      />
      <mesh
        name="国际学术交流中心"
        castShadow
        receiveShadow
        geometry={nodes.国际学术交流中心.geometry}
        material={nodes.国际学术交流中心.material}
        position={[3.03635, 0.66267, 2.4291]}
        children={<Label text="国际学术交流中心"></Label>}
      />
      <mesh
        name="昌海楼"
        castShadow
        receiveShadow
        geometry={nodes.昌海楼.geometry}
        material={nodes.昌海楼.material}
        position={[2.53033, 0.46038, 2.97825]}
        children={<Label text="昌海楼"></Label>}
      />
      <mesh
        name="空间研究院"
        castShadow
        receiveShadow
        geometry={nodes.空间研究院.geometry}
        material={nodes.空间研究院.material}
        position={[-0.71817, 0.42921, 2.32672]}
        children={<Label text="空间研究院"></Label>}
      />
      <mesh
        name="图书馆"
        castShadow
        receiveShadow
        geometry={nodes.图书馆.geometry}
        material={nodes.图书馆.material}
        position={[-1.49487, 1.5139, 2.49133]}
        children={<Label text="图书馆"></Label>}
      />
      <mesh
        name="安保楼"
        castShadow
        receiveShadow
        geometry={nodes.安保楼.geometry}
        material={nodes.安保楼.material}
        position={[-2.63907, 0.42921, 2.56249]}
        children={<Label text="安保楼"></Label>}
      />
      <mesh
        name="天健垃圾场"
        castShadow
        receiveShadow
        geometry={nodes.天健垃圾场.geometry}
        material={nodes.天健垃圾场.material}
        position={[-2.71802, 0.32366, 4.61587]}
        children={<Label text="天健垃圾场"></Label>}
      />
      <mesh
        name="第12实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.第12实验大楼.geometry}
        material={nodes.第12实验大楼.material}
        position={[6.02777, 0.62687, 3.55836]}
        children={<Label text="第12实验大楼"></Label>}
      />
      <mesh
        name="第56实验大楼"
        castShadow
        receiveShadow
        geometry={nodes.第56实验大楼.geometry}
        material={nodes.第56实验大楼.material}
        position={[5.96411, 0.62687, 5.06083]}
        children={<Label text="第56实验大楼"></Label>}
      />
      <mesh
        name="水电楼"
        castShadow
        receiveShadow
        geometry={nodes.水电楼.geometry}
        material={nodes.水电楼.material}
        position={[-4.25363, 0.47732, 0.9592]}
        children={<Label text="水电楼"></Label>}
      />
      <mesh
        name="办公楼"
        castShadow
        receiveShadow
        geometry={nodes.办公楼.geometry}
        material={nodes.办公楼.material}
        position={[-2.25519, 0.47732, -0.47299]}
        children={<Label text="办公楼"></Label>}
      />
      <mesh
        name="swimPool"
        castShadow
        receiveShadow
        geometry={nodes.swimPool.geometry}
        material={materials["Swimming Pool Tile Procedural.001"]}
        position={[-8.2608, 0.35089, -3.89916]}
      />
      <group name="白求恩广场" position={[7.32333, 0.21737, 3.39442]}>
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["Square Grass"]}
        />
        <mesh
          name="Circle001_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials["Square Grey Stone"]}
        />
        <mesh
          name="Circle001_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials["Square Brown Stone"]}
        />
      </group>
      <mesh
        name="人才公寓1栋"
        castShadow
        receiveShadow
        geometry={nodes.人才公寓1栋.geometry}
        material={nodes.人才公寓1栋.material}
        position={[9.37268, 1.50611, 6.56151]}
        children={<Label text="人才公寓1栋"></Label>}
      />
      <mesh
        name="map_2osm_forest"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_forest.geometry}
        material={materials["forest.001"]}
        position={[-0.38123, 0.21803, 0.79995]}
      />
      <mesh
        name="map_2osm_roads_primary"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_primary.geometry}
        material={materials["roads_primary.001"]}
        position={[-0.38123, 0.21934, 0.79995]}
      />
      <mesh
        name="map_2osm_roads_residential"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_residential.geometry}
        material={materials["roads_residential.001"]}
        position={[-0.38123, 0.21934, 0.79995]}
      />
      <mesh
        name="map_2osm_roads_secondary"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_secondary.geometry}
        material={materials["roads_secondary.001"]}
        position={[-0.38123, 0.21934, 0.79995]}
      />
      <mesh
        name="map_2osm_roads_service"
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_roads_service.geometry}
        material={materials["roads_service.001"]}
        position={[-0.38123, 0.21934, 0.79995]}
      />
      <mesh
        name="湖"
        castShadow
        receiveShadow
        geometry={nodes.湖.geometry}
        material={materials["water.001"]}
        position={[-0.38123, 0.21737, 0.79995]}
        children={<Label text="湖"></Label>}
      />
      <mesh
        name="正气广场"
        castShadow
        receiveShadow
        geometry={nodes.正气广场.geometry}
        material={materials["forest.001"]}
        position={[-4.02313, 0.24942, -1.54202]}
        children={<Label text="正气广场"></Label>}
      />
      <mesh
        name="Plane014"
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["forest.001"]}
        position={[-3.76456, 0.22521, 2.74376]}
      />
      <mesh
        name="网球场"
        castShadow
        receiveShadow
        geometry={nodes.网球场.geometry}
        material={materials["Material.003"]}
        position={[1.20068, 0.2192, 4.77883]}
        children={<Label text="网球场"></Label>}
      />
      <mesh
        name="basketballCount"
        castShadow
        receiveShadow
        geometry={nodes.basketballCount.geometry}
        material={materials["Material.003"]}
        position={[1.51385, 0.2192, 5.1972]}
      />
      <mesh
        name="篮球场"
        castShadow
        receiveShadow
        geometry={nodes.篮球场.geometry}
        material={materials["Material.003"]}
        position={[0.93365, 0.2192, 5.30566]}
        children={<Label text="篮球场"></Label>}
      />
      <mesh
        name="basketballCourt"
        castShadow
        receiveShadow
        geometry={nodes.basketballCourt.geometry}
        material={materials["Material.003"]}
        position={[0.91586, 0.2192, 5.30901]}
      />
      <group name="休闲运动场" position={[-9.46924, 0.21737, -3.26391]}>
        <mesh
          name="Circle005"
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle005_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle005_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle005_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle005_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle005_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle005_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <group name="运动场" position={[6.147, 0.21737, 6.22569]}>
        <mesh
          name="Circle014"
          castShadow
          receiveShadow
          geometry={nodes.Circle014.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle014_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle014_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle014_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle014_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <group name="sportsField" position={[0.95148, 0.21714, 4.14498]}>
        <mesh
          name="Circle013"
          castShadow
          receiveShadow
          geometry={nodes.Circle013.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle013_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle013_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle013_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle013_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <group name="sportsField001" position={[-6.47137, 0.2788, -4.64413]}>
        <mesh
          name="Circle016"
          castShadow
          receiveShadow
          geometry={nodes.Circle016.geometry}
          material={materials["Playground Ground"]}
        />
        <mesh
          name="Circle016_1"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_1.geometry}
          material={materials["Football-Playground-mark.003"]}
        />
        <mesh
          name="Circle016_2"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_2.geometry}
          material={materials["Football Playground Dark.003"]}
        />
        <mesh
          name="Circle016_3"
          castShadow
          receiveShadow
          geometry={nodes.Circle016_3.geometry}
          material={materials["Football Playground Light.003"]}
        />
      </group>
      <mesh
        name="月亮湖"
        castShadow
        receiveShadow
        geometry={nodes.月亮湖.geometry}
        material={materials["water.001"]}
        position={[7.96533, 0.21737, 4.01887]}
        children={<Label text="月亮湖"></Label>}
      />
      <mesh
        name="floor"
        receiveShadow
        geometry={nodes.floor.geometry}
        material={nodes.floor.material}
        position={[-0.38123, 0.08301, 0.79995]}
      />
    </group>
  );
}

useGLTF.preload(modelUrl);
